### PR TITLE
LZ4CompressionUtils: replace deprecated fast decompression

### PR DESCRIPTION
**Pull request by dwlsalmeida**
LZ4_decompress_fast() is deprecated and such call produces a warning.

As RAMSES is configured with -Werror by default this breaks compilation.

This commit calls LZ4_decompress_safe() instead, which is a bit slower.

Signed-off-by: Daniel W. S. Almeida <dwlsalmeida@gmail.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
Great to see this, Daniel.  A good first contribution and thanks for using good git commit messages.

It can be improved a little bit more:
Title (first line)
```
    LZ4CompressionUtils: remove call to deprecated function
```
I would propose
```
    LZ4CompressionUtils: replace deprecated fast decompression
```

Since you actually replaced it instead of removed it, and since this sentence gives a little bit more information about what it actually is without being much longer.

For the body, the extra lines are not needed and the words "This commit" are redundant, so you can just as well say "Now using" or if you wish even imperative tense such as "Use LZ4_decompress_safe() instead, which is a bit slower."

A good goal is basically to convey as much information as possible with few words, but of course you use as many words as are needed to be clear and always using correct English.

```
LZ4_decompress_fast() is deprecated and produces a warning. As RAMSES is
configured with -Werror by default this breaks compilation. Now using
LZ4_decompress_safe() instead, which is a bit slower.

<sign-off-line>
```

(sorry for being picky.  Just some mentor guidance :)

**Comment by gunnarx** [comment]
An interesting note by the way:  I didn't check which version of the library is being used and when this changed, but looking at the latest master, [this comment](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L634) suggests that _safe is now actually faster than _fast :)

**Comment by dwlsalmeida** [comment]
@gunnarx

How do I go about fixing this once a PR has already been sent? I ask because I once amended and force pushed and got told that was slightly undesirable.

I would prefer having less lines in the commit message - or actually just one line since this is short - but that was at odds with having <74 characters per line.

**Comment by violinyanev** [comment]
Hi guys,

@Gunnar thanks for the review - I completely agree.
@Daniel the way we usually modify PRs in general is by adding more commits
on top and pushing in a forward only fashion. In this case, since Gunner
asked for a change in the commit message, you can only amend the commit -
so a force push in not avoidable. But maintainers know that - Gunner will
not be surprised that when he fetches your branch after the fix, it will be
force overridden. Generally though, if a maintainer asks to fix something
in the commit content, you create the fixes as incremental patches, unless
explicitly asked otherwise.

That being said, I have a rule of my own - if I happen to amend a patch
anyway (for whatever reason), I also rebase it to the latest version of the
target branch. That way you can avoid merge conflicts which sometimes
happen if your PR ages a little bit.

Thanks for the contribution! Fix the commit message and I will take it in.

Regards,
Violin

**Comment by gunnarx** [comment]
Yes, as Violin indicated, a change in the commit message only definitely would not make sense to do in a new commit, which would be empty, but with a new message.  Amend and force-push this.

> But maintainers know that - Gunner will not be surprised that when he fetches your branch after the fix, it will be force overridden

Yes, I actually *never* get surprised if a PR has been force pushed and I basically look at them fresh every time.  The workflow we use in GDP is to frequently update and force push PRs - both the submitter and the maintainer would do this occasionally - for example a maintainer might jump in and rebase it at any time, if this was not done by the submitter, and so on.

Overall, in my opinion a PR has not yet been accepted into the tree, and therefore can/should be freely rewritten as much as you want (and GitHub shows clearly when this happens anyway so it will be noticed).  But I admit I haven't really been much involved in reviewing such large PRs that I had to worry about re-reviewing all of it from the beginning.  When that is the case, of course working with incremental changes at first will be easier to review and check that the exact request was actually done. (And this may also be many maintainers preference because of that), but I hope that is **if** everyone has the understanding that the history in the PR will be cleaned up before merging it.  There is no point in bringing "mistakes" into the master branch history, since this is avoidable by fixing while it is still a PR, IMHO.

Ideally, the reviewer will clarify what they want.  Otherwise you'll have to ask the maintainer what they prefer for their project.

**Comment by dwlsalmeida** [comment]
@gunnarx @violinyanev 

Should be good to go now. Sorry for these extra steps: I messed up a bit along the way.

**Comment by GENIVI-Ramses** [comment]
Looks good! But we have to test it internally before merging - production systems depend heavily on data compression and speed and we need to test the performance first. Might take a while! If the warning is annoying - keep in mind it is possible to disable warnings=errors setting over a cmake option (see top-level cmake file)

**Pull request closed without merging**
